version: '3.9'

services:
  # MongoDB services
  guatapay_db:
    container_name: guatapay-vtex-bd
    image: mongo:latest
    command: mongod --port 27031
    restart: unless-stopped
    volumes:
      - /home/conexa/apps/mongo-guatapay-vtex:/data/db
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - guatapay-back-network

  # Node API services
  guatapay:
    container_name: guatapay-back-vtex
    build: .
    restart: unless-stopped
    working_dir: "/opt/app/backend-vtex"
    ports: 
      - ${PORT_OUT}:${PORT_IN}
    networks:
      - guatapay-back-network
    depends_on:
      - guatapay_db
    environment:
       PORT: ${PORT_IN}
       NODE_ENV: ${NODE_ENV}
       API_URL: ${API_URL}
       FRONTEND_URL: ${FRONTEND_URL}
       CRYPTOJS_SECRET_KEY: ${CRYPTOJS_SECRET_KEY}
       MONGODB_URL: ${MONGODB_URL}
       JWT_SECRET: ${JWT_SECRET}
networks:
  guatapay-back-network:
    name: guatapay-back-network
    driver: bridge
